stages:       
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Building code..."
    - echo "Build complete."

python-tests:
  image: python:2.7.18-stretch
  stage: test
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - make python-tests
  
selenium-tests:
  image: joyzoursky/python-chromedriver:2.7-selenium
  stage: test
  before_script:
    - pip install -r frontend/requirements.txt
  script:
    - make selenium-tests

jest-tests:
  image: node:latest
  stage: test
  before_script:
    - make update-front
  script:
    - make jest-tests

postman-tests:
  stage: test
  image: postman/newman
  script:
    - cd backend
    - newman run Postman.json

deploy-dev-job:     
  only:
      variables:
        - $CI_COMMIT_BRANCH == "dev"
  stage: deploy  
  environment: development
  script:
    - git checkout dev
    - echo "Deploying development version..."
    - echo "Development version successfully deployed."

deploy-prod-job:     
  only:
      variables:
        - $CI_COMMIT_BRANCH == "main"
  stage: deploy  
  environment: production
  script:
    - git checkout main
    - echo "Deploying production version..."
    - echo "Production version successfully deployed."



