stages:       
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Building code..."
    - echo "Build complete."

python-tests:
  image: python:2.7.18-stretch
  stage: test
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - make python-tests
  
selenium-tests:
  image: joyzoursky/python-chromedriver:2.7-selenium
  stage: test
  services:
    - selenium/standalone-chrome
  before_script:
    - pip install -r frontend/requirements.txt
    - cd front-end
    - apt-get update -q -y
    - apt-get --yes install libnss3
    - apt-get --yes install libgconf-2-4
    - apt-get install libx11-xcb1
    
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
    - apt-get update -q -y 
    - apt-get install -y google-chrome-stable
    - apt-get install -yqq unzip
    - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
    - unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
  script:
    make selenium-tests

deploy-dev-job:     
  only:
      variables:
        - $CI_COMMIT_BRANCH == "dev"
  stage: deploy  
  environment: development
  script:
    - git checkout dev
    - echo "Deploying development version..."
    - echo "Development version successfully deployed."

deploy-prod-job:     
  only:
      variables:
        - $CI_COMMIT_BRANCH == "main"
  stage: deploy  
  environment: production
  script:
    - git checkout main
    - echo "Deploying production version..."
    - echo "Production version successfully deployed."



