stages:       
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Building code..."
    - echo "Build complete."

python-test:
  image: python:2.7.18-stretch
  stage: test
  before_script:
    - pip install -r backend/requirements.txt
  script:
    - make python-tests

test-job:   
  stage: test    
  script:
    - echo "Running unit tests... This will take about 5 seconds."
    - sleep 5
    - echo "Unit tests complete."

deploy-dev-job:     
  only:
      variables:
        - $CI_COMMIT_BRANCH == "dev"
  stage: deploy  
  environment: development
  script:
    - git checkout dev
    - echo "Deploying development version..."
    - echo "Development version successfully deployed."

deploy-prod-job:     
  only:
      variables:
        - $CI_COMMIT_BRANCH == "main"
  stage: deploy  
  environment: production
  script:
    - git checkout main
    - echo "Deploying production version..."
    - echo "Production version successfully deployed."



